version: '3'
services:
  app:
    container_name: pro-net-api
    build: .
    ports:
      - '8081:8081'
    environment:
      GO_WORK_DIR: /go/pro-net-api
  mongo:
    image: mongo
    restart: always
