version: '3'
services:
  api:
    container_name: pro-net
    hostname: backend
    build: ./
    volumes:
      - ./src:/var/www/pro-net-api/src
    ports:
      - "3000:3000"
      - "9222:9222"
    env_file: ./docker/environments
    links:
      - pro-net-api-db
    depends_on:
      - pro-net-api-db
  pro-net-api-db:
    image: 'mongo:latest'
    container_name: mongodb
    # environment:
    #   - MONGO_DATA_DIR=/data/db
    #   - MONGO_LOG_DIR=/dev/null
    volumes:
      - db_data:/var/lib/mongodb'
    ports:
      - '27017:27017'
    command: mongod --smallfiles --logpath=/dev/null
volumes:
  db_data:
